mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('recipes.urls')),
    path('', include('gsheets.urls')),
    path('admin/', admin.site.urls),
]

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('add/', views.add, name='add'),
    path('add/add_new', views.add_new, name='add_new'),
]

recipes/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from gsheets import mixins
from uuid import uuid4


class Recipe(mixins.SheetSyncableMixin, models.Model):
    """
    a class for a single recipe
    """
    sheet_id = '1FTTISKHNJEMgsGB18AqrzM3JCXu8YpPdVSrc3f3GV5g'
    recipe_source = models.CharField(max_length=200, default='')
    name = models.CharField(max_length=200)
    source_name = models.CharField(max_length=200, null=True, blank=True)
    time = models.CharField(max_length=200, null=True, blank=True)
    new = models.BooleanField(default=False)
    ingredients = models.TextField(null=True, blank=True)

    class Meta:
        ordering = ['name']
    
    def __str__(self) -> str:
        return self.name

# class Ingredient(models.Model):
#     """
#     class for a single ingredient in a recipe
#     """
#     name = models.CharField(max_length=200)
#     recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.name

# class Instruction(models.Model):
#     """
#     class for single instruction in a recipe. The primary key will define the step number
#     """
#     step_text = models.TextField()
#     recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

#     def __str__(self):
#         return self.step_text

# class Source(models.Model):
#     recipe = models.OneToOneField(Recipe, on_delete=models.CASCADE)

# class Book(Source):
#     title = models.CharField(max_length=200)
#     page_number = models.IntegerField()

#     def __str__(self) -> str:
#         return self.title

# class Website(Source):
#     website_url = models.URLField()

#     def __str__(self) -> str:
#         return self.website_url

recipes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Recipe #Ingredient, Instruction, Book, Website

class IndexView(generic.ListView):
    template_name = 'recipes/index.html'
    context_object_name = 'recipe_list'

    def get_queryset(self):
        """
        return all recipes
        """
        return Recipe.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(IndexView, self).get_context_data(**kwargs)
        # Create any data and add it to the context
        context['new_recipe_list'] = Recipe.objects.filter(new=True)
        context['old_recipe_list'] = Recipe.objects.filter(new=False)
        context['recipe_list'] = Recipe.objects.all()
        return context

class DetailView(generic.DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'

    def get_queryset(self):
        """
        returns all recipes
        """
        return Recipe.objects.all()

def index(request):
    return render(request, 'recipes/index.html', {'recipe_list': Recipe.objects.order_by('-name')})

def detail(request, recipe_id):
    r = get_object_or_404(Recipe, pk=recipe_id)
    return render(request, 'recipes/detail.html', {'recipe': r})

def add(request):
    return render(request, 'recipes/add.html')

def add_new(request):
    name = request.POST['title']
    time = request.POST['time']
    if time=='':
        time = None
    ingredients_text = request.POST['ingredients']

    new = request.POST['new'] == 'on'

    recipe = Recipe(name=name, time=time, new=new, ingredients=ingredients_text)

    recipe.save()
    
    # website_url = request.POST['website']
    # if not website_url:
    #     book_title = request.POST['book']
    #     page_number = request.POST['page_number']
    #     # Book(recipe=recipe, title=book_title, page_number=page_number)
    # # else:
    #     # Website(recipe=recipe, website_url=website_url)

    # instructions_text = request.POST['instructions']
    
    # for ingredient in ingredients_text.split(','):
    #     recipe.ingredient_set.create(name=ingredient)
    
    # for instruction in instructions_text.split('\n'):
    #     recipe.instruction_set.create(step_text=instruction)
    
    # recipe.save()
    
    return HttpResponseRedirect(reverse('recipes:add'))

recipes/templates/recipes/add.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add new recipe</title>
    </head>
    <body>
        <h2>Add New Recipe</h2>
        <form action="{% url 'recipes:add_new' %}", method="POST">
            {% csrf_token %}
            <label for="title">Title:</label>
            <input type="text" id="title" name="title"><br>

            <label for="recipe_status_new">New recipe?</label>
            <input type="checkbox" id="recipe_status_new" name="recipe_status_new"><br>

            <label for="time">Time:</label>
            <input type="number" id="time" name="time"><br>
            
            <label for="source">URL or Book title and page:</label>
            <input type="text" id="source" name="source"><br>
            <!-- try auto fill option -->

            <label for="ingredients">Ingredients:</label><br>
            <textarea id="ingredients" name="ingredients", rows="5" cols="50"></textarea><br>
            <label for="instructions">Instructions:</label><br>
            <textarea id="instructions" name="instructions", rows="5" cols="50"></textarea><br>

            <input type="submit" value="Add">
        </form>
    </body>
</html>

recipes/templates/recipes/base_generic.html
<!DOCTYPE html>
<html>
    <head>
        {% block titile %}<title>Home page</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet"href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'recipes:index' %}">Home</a></li>
                        <li><a href="">New recipes</a></li>
                        <li><a href="">Old recipes</a></li>
                    </ul>
                {% endblock %}
                </div>
                <div class="col-sm-10">{% block content %}{% endblock %}</div>
            </div>
        </div>
    </body>
</html>

recipes/templates/recipes/detail.html
{% extends "recipes/base_generic.html" %}

{% block title %}
{{ recipe.name }}
{% endblock %}

{% block content %}
    <h1>{{ recipe.name }}</h1>
    <a>
        Time: {{ recipe.time }} min.
    </a>
    <h2>Ingredients</h2>
    <ul>
        {% if recipe.ingredients %}
            {% for ingredient in recipe.ingredients.split %}
            <li>{{ingredient.name}}</li>
            {% endfor %}
        {% else %}
            <li>None</li>
        {% endif %}
    </ul>
    <!-- <h2>Instructions</h2>
    <ol>
        {% if recipe.instruction_set.all %}
            {% for instruction in recipe.instruction_set.all %}
            <li>{{instruction.step_text}}</li>
            {% endfor %}
        {% else %}
            <li>None</li>
        {% endif %}
    </ol> -->
{% endblock %}

recipes/templates/recipes/index.html
{% extends "recipes/base_generic.html" %}

{% block title %}
Recipe index
{% endblock %}

{% block content %}
    <h1>Recipes</h1>
    <div class="row">
        <div class="col-sm-3">
            <p>New recipes are shown below</p>
            {% if new_recipe_list %}
                <ul>
                    {% for recipe in new_recipe_list %}
                    <li><a href="{% url 'recipes:detail' recipe.id %}">{{ recipe.name }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No new recipes available</p>
            {% endif %}
        </div>
        <div class="column">
            <p>Old recipes are shown below</p>
            {% if old_recipe_list %}
                <ul>
                    {% for recipe in old_recipe_list %}
                    <li><a href="{% url 'recipes:detail' recipe.id %}">{{ recipe.name }}</a></li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No recipes available</p>
            {% endif %}
        </div>
    </div>
{% endblock %}